### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by Ksdmg** [GeorgDangl/WebDocu#3]
The following packages are not available:
```
Dangl.Identity.Client.Mvc
Dangl.Identity.ApiClient
```
This prevents me from building the project. I would like to use it for internal documentation.

**Comment by GeorgDangl** [comment]
Hey @Ksdmg, thank you for raising this issue!

That's a good point😀 We changed to using Dangl.Identity as OpenID provider some time ago, and looks like not all packages for it are on the public NuGet feed.

I'm pretty sure that we can publish them, will just need a few days to review it.

**Comment by Ksdmg** [comment]
Hello @GeorgDangl , any updates on this?

**Comment by GeorgDangl** [comment]
Hey @Ksdmg, sorry for the late response, but here it is😀

We've made the dependencies public, so you should now be able to build and test the project.
