### ISSUE TITLE
Cannot resolve all Nuget Packages

### ISSUE THREAD

**Issue by unstepe** [GeorgDangl/WebDocu#5]
![image](https://github.com/GeorgDangl/WebDocu/assets/128090393/d1230a4c-ca64-401b-b763-90f50cff6c8e)

**Comment by GeorgDangl** [comment]
Hey @unstepe, can you try again? I think the project now builds, with the exception of one migration project (which you can ignore).

I've removed some obsolete dependencies just now.

**Comment by GeorgDangl** [comment]
I'll be bold and close the issue, just reopen if you're still having trouble😀 Doing a bit of cleanup today.

**Comment by unstepe** [comment]
It still cannot resolve the following packages:

![image](https://github.com/GeorgDangl/WebDocu/assets/128090393/97c62bc9-ef42-4cbf-93ad-ae650b3fa007)

**Comment by unstepe** [comment]
Maybe I use the false myget repo?
https://www.myget.org/gallery/dangl

**Comment by unstepe** [comment]
@GeorgDangl i cannot find this package:
![image](https://github.com/GeorgDangl/WebDocu/assets/128090393/1767b030-69fe-462f-83a5-5190ed932b89)

I cannot reopen the ticket...

**Comment by GeorgDangl** [comment]
No, the package source is fine, that's just an internal package which we have not published. But, I think this is only referenced by one of the migration projects. You can safely ignore them, and just unload them in Visual Studio. We used them a few years ago when we moved from an IIS based install to Azure.

**Comment by unstepe** [comment]
Ok. Thank you.
Another problem:
I cannot install Dangl.Identity.Client.Mvc

NU1101: Das Paket "Dangl.Identity.ApiClient

**Comment by GeorgDangl** [comment]
Hey @unstepe, sorry about that, it was an error on my side!

I saw that the `Dangl.Identity.ApiClient` package actually wasn't publicly available on NuGet, and also not on the MyGet Feed (which we've kind of deprecated, due to the reliability issues with MyGet in the past).

I've just pushed an update, can you try it again?

**Comment by unstepe** [comment]
It works now.
Thank you for that.
